name: delivery_app_emilio_puigcerver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0" # Compatible con Dart 3.5.4

dependencies:
  cloud_firestore: ^5.4.0
  collection: ^1.17.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.0
  firebase_core: ^3.3.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_credit_card: ^3.0.2
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^5.3.0
  intl: ^0.20.0
  onesignal_flutter: ^3.5.4
  path_provider: ^2.1.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  unity_ads_plugin: ^0.3.22
  workmanager: ^0.5.0

dev_dependencies:
  flutter_lints: ^1.0.0 # Versión compatible
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/images/burgers/
    - lib/images/sides/
    - lib/images/salads/
    - lib/images/drinks/
    - lib/images/desserts/
    - lib/assets/onboarding1.png
    - lib/assets/onboarding2.png
    - lib/assets/onboarding3.png
